import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex gap-2 bg-black justify-center h-[200px]">
        <Image
          src="/rocket.svg"
          alt="rocket"
          width="0"
          height="0"
          style={{ width: "22px", height: "36px" }}
          className="cursor-pointer my-auto"
        />
        <h1 className="flex py-12 text-[#5e60CF] font-black gap-1 text-[40px] my-auto"><span className="text-[#4EA8DE]">Todo</span> App</h1>
        </div>
        {children}
      </body>
    </html>
  );
}
